server:
  port: 8130

spring:
  profiles:
    active: dev # 环境设置
  application:
    name: service-oss # 服务名

txy:
  oss:
    secretId: AKIDfBSXO0LQFo7AxUklW1FDvNaZHjvrWv3u
    secretKey: bx2rQjmbAUZP2PWMzMTJtDI7f06wVore
    regionName: ap-nanjing
    bucketName: srb-file-1304977421



